### ISSUE TITLE
Feature request: Customizable AllowedIPs (Wireguard)

### ISSUE THREAD

**Issue by Hey** [qdm12/gluetun#1066]
### What's the feature 🧐

This would allow local network access with tools like https://www.procustodibus.com/blog/2021/03/wireguard-allowedips-calculator/

**Comment by qdm12** [comment]
I added that feature on image `qmcgaw/gluetun:pr-1291` you can use `WIREGUARD_ALLOWED_IPS=0.0.0.0/0` for example (comma separated values). See #1291 for code changes. Please let me know if it works for you.

@hellodword I think @Hey meant to VPN only to access the remote LAN (on the vpn server side), not the local (gluetun side) LAN.

**Comment by qdm12** [comment]
Does it work? Thanks!

**Comment by Hey** [comment]
Sorry, I am not a Gluetun user anymore.

**Comment by Covernel** [comment]
> Does it work? Thanks!

It works on surfshark wireguard. hope it can merge to main release.
https://github.com/qdm12/gluetun/discussions/1467

**Comment by goooroooX** [comment]
Guys, is this feature works? WIREGUARD_ADDRESSES seems to be absent in default env variables...

**Comment by qdm12** [comment]
This is merged in the latest image and will be part of future release v3.36.0.
You can now use `WIREGUARD_ALLOWED_IPS` which defaults to `0.0.0.0/0` and `::/0` (if ipv6 supported)

@goooroooX please read next time, before spreading false and out of scope information. This issue is about `WIREGUARD_ALLOWED_IPS`, which was in pull request image `qmcgaw/gluetun:pr-1291` for testing (if you would had read a few lines above).

> WIREGUARD_ADDRESSES seems to be absent in default env variables...

`WIREGUARD_ADDRESSES` [has been in the Dockerfile for 17 months](https://github.com/qdm12/gluetun/blame/master/Dockerfile#L100) and is well documented in the Wiki.

> looks like option is NOT working. Can you please implement it?

It's working well.

> This must-have feature for cross-client communications.

That doesn't make any sense

**Comment by goooroooX** [comment]
@qdm12, so much angry for nothing. Yeah, I meant WIREGUARD_ALLOWED_IPS, indeed. Copy-paste issue makes you so unhappy, I'm sorry.

**Comment by qdm12** [comment]
> so much angry for nothing.

Did you try the Docker image with the PR image tag `qmcgaw/gluetun:pr-1291` and it didn't work?

**Comment by goooroooX** [comment]
My comment was related to the recent several comments, this one in particular: "hope it can merge to main release". It was about the main branch. So yeah, I dod not test pr branch, I did test main.

**Comment by qdm12** [comment]
So you understood it wasn't in the latest image / main branch, but still commented to ask for it and stating the obvious (not in the latest image). If there is an issue opened, there is no point re-asking for the same issue, that's why we have issue tracking.

I receive about 5 comments per day which I try to answer to, and this takes a lot of time. When I read such a low quality and misleading comment (`UPD: looks like option is NOT working.` although it was working), you also waste my time (and other's time involved on this issue) so yes it makes me angry and not for nothing.
