### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by YunhaoJiang** [qdm12/gluetun#1081]
### Is this urgent?

No

### Host OS

Synology DSM 7.2

### CPU arch

x86_64

### VPN service provider

Private Internet Access

### What are you using to run the container

docker-compose

### What is the version of Gluetun

877617c

### What's the problem 🤔

The log keep showing that cannot dial: dial tcp4 [SOME IP ADDRESS]:443: i/o timeout stdout 22:57:32 

### Share your logs

```plain text
2022-07-26T22:57:31-05:00 INFO [healthcheck] unhealthy: cannot dial: dial tcp4 [SOME IP ADDR]: i/o timeout stdout 22:57:32 
2022-07-26T22:57:32-05:00 INFO [healthcheck] healthy! stdout 22:58:18
2022-07-26T22:58:18-05:00 INFO [healthcheck] unhealthy: cannot dial: dial tcp4 [SOME IP ADDR]:443: i/o timeout stdout 22:58:20
2022-07-26T22:58:20-05:00 INFO [healthcheck] healthy! stdout 00:35:04
```

### Share your configuration

```yml
version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    hostname: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8088:8088
    volumes:
      - /volume1/docker/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=[USERNAME]
      - OPENVPN_PASSWORD=[PASSWD]
      - SERVER_REGIONS=[REGION]
      - TZ=[TIMEZONE]
      - PUID=1026
      - PGID=101
```

**Comment by qdm12** [comment]
This happens when the healthcheck (querying cloudflare.com:443) fails. It runs 5s after a successful check, and 1s after a failed check. If it goes back to a success after a fail, it logs `healthy!`. If it stays unhealthy for 6s, the vpn gets restarted.

Please read https://github.com/qdm12/gluetun/wiki/Healthcheck to know more how it works. You can also configure it to your tastes with https://github.com/qdm12/gluetun/wiki/Health-options
