### ISSUE TITLE
ERROR: for gluetun  Cannot start service gluetun: error gathering device information while adding custom device "/dev/net/tun": no such file  or directoryBug: 

### ISSUE THREAD

**Issue by klotan** [qdm12/gluetun#1088]
### Is this urgent?

Yes

### Host OS

LXC containder Docker

### CPU arch

x86_64

### VPN service provider

NordVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

latest

### What's the problem 🤔

When i try to deploy the container i get this error:
ERROR: for gluetun  Cannot start service gluetun: error gathering device information while adding custom device "/dev/net/tun": no such file or directory

Im kinda new to docker so don´t have a ton of experience.

### Share your logs

```plain text
don´t know where to find
```

**Comment by frepke** [comment]
Share your logs please

Open your terminal and navigate to the location of your Gluetun yaml file.
Type `docker-compose logs gluetun` or `docker compose logs gluetun` for the logs.
When you have Portainer running, you can find the logs in there.

**Comment by qdm12** [comment]
```
ERROR: for gluetun Cannot start service gluetun: error gathering device information while adding custom device "/dev/net/tun": no such file or directory
```

that error comes from your host / docker runtime, not Gluetun. There is no log since it doesn't even start.

Gluetun handles on most (not all) systems the creation of that /dev/net/tun file, so you can try removing the /dev/net/tun mapping from your docker service config and see if it works.
If it doesn't, you'll have to create it on your host. Sometimes just `modprobe tun` does it, or you might have to google your way around.

Closing this since it's not really a gluetun bug, but feel free to add comments.

Also thanks @frepke for your input 😉

**Comment by klotan** [comment]
Thx, it works when i manually creates the tun file.
