### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by auroraborealis88** [qdm12/gluetun#1321]
### Is this urgent?

None

### Host OS

Linux Debian

### CPU arch

x86_64

### VPN service provider

ProtonVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

2022-12-15T10:02:42.178Z (commit 490693b)

### What's the problem 🤔

I'm not an IT guy, but try to make firefox work inside a container that goes through gluetun vpn. Those 2 services in a docker-compose yml. 

I previously didn't get the dns working with NordVPN with DOT=off and a valid nordpvn DNS. The "Your credentials might be wrong" message that several other people got, I can see on this site. After some docker-compose down and up again, it all worked. Hurra. Firefox works, and ipleak.net shows nordvpn both IP and DNS. But that was a temporary victory. Next time, not only the nordvpn DNS stopped working, but also the IP. It never worked again. "Your credentials might be wrong". OK, perhaps nordvpn is shitty. 

Then I tried the porotonvpn free service, to a test before really changing VPN provider. Correct openvpn user and login, FREE_ONLY=on. It worked. But of course the DNS is the disgusting cloudflare DNS. I just can't see why you want to give all your users browsing history to them. "They promise to be private". Yeah, sure. You may as well stop using a vpn if you are so naive. WHY have you gone all in to DNS over TLS? Because it's "new and cool"? Dumb.

I tried DOT=off with protonvpn. Not even added a dns address yet - and gluetun stopped working. No internet connection again. I got the "Your credentials might be wrong" message! Then I did add a protonvpn dns address, and of course still no internet, no gluetun working.

I'm not an IT guy, but it should be possible for normal people who are willing to do some reading to use containers for VPN. Gluetun was recommended by various youtube channels. But I find it unstable and prohibitively complicated.
And why, WHY this hard-on for Cloudflare? Why not make a gluetun WITHOUT that fucking oligopoly corporation or the others (even google dns over tls can be chosen. THANK YOU. Not). The environment variables that are supposed to remove that fuck (Cloudflare) clearly don't work, not just for me, but for many other gluetun users. 

If gluetun is to be a serious alternative for usage and donations from privacy-minded people, you must make a DNS over TLS-free version. Completely cloudflare and google-free.

### Share your logs

```plain text
I note that the lines from yml are written in the logs. They are full of comments with cursing and other less friendly language. May remove them and then post the logs. In the meantime you can see the logs posted by other people who didn't get the non-clouflare dns working.
```

### Share your configuration

```yml
maybe later, if there is any use.
```

**Comment by qdm12** [comment]
Ok so that's a lot of hate to take in, especially on new year eve. I'm the sole maintainer and kinda going through a burn out, so, as you say, **THANK YOU. Not**

But since I'm a human being with arguably better ethics, I'll help you learn a thing or two.

Your authentication error comes from your vpn provider or your credentials, it has nothing to do with dns. No network communication is done before the vpn tunnel is up.

Cloudflare is often ahead of everyone else in terms of DNS. They were the first ones to support DNS over TLS, so the default choice is historic and to keep retro-compatibility.

You can choose multiple DoT providers with a csv value, see https://github.com/qdm12/gluetun/wiki/DNS-options (if at least you would had read it).
That's the best option privacy wise, since you split your traffic with several entities. Even if one of them is google, it's just a part of your traffic so kinda useless (especially coming from a vpn ip).

Using the vpn provider dns is putting your trust in the vpn provider which can totally track you, sell your dns traffic and store it even if they say they don't (on top of that they have some information on you like credit card linked to your dns traffic). A lot worse than just using Cloudflare for example.

Not using DNS over TLS means any device on the route between the vpn server and the dns server can be read and even modified. That also means a single entity could easily access all your traffic.

There is also #137 which is about to be done, which would allow to pick a dns over tls/https server of your choice (but would you have any server in mind not listed already???)
