### ISSUE TITLE
Wiki issue: Update NordVPN to include support for `SERVER_GROUPS`

### ISSUE THREAD

**Issue by vdrover** [qdm12/gluetun#1541]
### URL to the Wiki page

https://github.com/qdm12/gluetun/wiki/NordVPN

### What's the issue?

Server groups are also supported. eg, you can use `SERVER_GROUPS` in docker compose instead of `SERVER_REGIONS`.

The current groups from NordVPN can be found in the CLI. For example:

```
$ sudo nordvpn groups
 > Africa_The_Middle_East_And_India
 > Double_VPN
 > Onion_Over_VPN
 > Standard_VPN_Servers
 > Asia_Pacific
 > Europe
 > P2P
 > The_Americas
```

**Comment by qdm12** [comment]
This data should be added through #1380 first

**Comment by qdm12** [comment]
Although what's the use case? 🤔 

The region group will now be taken into account (`The_Americas`, etc.) and you will be able to use the `SERVER_REGIONS` filter.

But the other ones, do they have any use? That would add a considerable amount of data to the servers data because each server has 3-5 groups, and given the high number of nordvpn servers (they make half of the servers data in gluetun!), that would add a few MBs to the Docker image which I would ideally avoid.

**Comment by vdrover** [comment]
I’m not asking to change the docker image. I’m saying that the current image already does support SERVER_GROUPS. Updating the wiki would save folks fumbling around like I did to see if it works :)

**Comment by qdm12** [comment]
`SERVER_GROUPS` is not even a defined environment variable, so it's simply ignored. Gluetun randomly picks any VPN server from all the servers available.

**Comment by vdrover** [comment]
Understood. 

Then to answer your use-case question, I was hoping to use random double_vpn servers.

**Comment by qdm12** [comment]
Ok cool, I created #1643 (which includes your request), please subscribe to that one instead 👍 Thanks!
