### ISSUE TITLE
Gluetun Country Selection with ExpressVPN throws an error

### ISSUE THREAD

**Issue by skibare87** [qdm12/gluetun#1602]
Even though I have been using this docker configuration for a while, it all of a sudden throws an error on the selected country despite being in the list. My docker file specifies this as:

- SERVER_COUNTRIES=France,Netherlands,Spain

I still get the below error though. It does seem to make the country string lower case, is there maybe an issue with string comparison?

2023-05-25T14:12:22-04:00 ERROR VPN settings: provider settings: server selection: for VPN service provider expressvpn: the country specified is not valid: value is not one of the possible choices: value **france**, choices available are Albania, Algeria, Andorra, Argentina, Armenia, Australia, Austria, Bahamas, Bangladesh, Belarus, Belgium, Bhutan, Bosnia And Herzegovina, Brazil, Brunei, Cambodia, Canada, Chile, Colombia, Costa Rica, Croatia, Cyprus, Czech Republic, Denmark, Ecuador, Egypt, Estonia, Finland, **France**, ...... etc

**Comment by Darrakas** [comment]
Check this out: https://github.com/qdm12/gluetun/issues/1600

Or use version 3.34

**Comment by Fastjur** [comment]
Just pointing out that this has been reported already :)

https://github.com/qdm12/gluetun/issues/1599

**Comment by qdm12** [comment]
The latest image `qmcgaw/gluetun` was fixed a few minutes ago by 7e325715c7a24da73447b29cec94b207bd950745.
The regression was introduced 2 days ago with a43973c093662c2b5521eb2e9e3aea053584e96b which did compare text taking care about case sensitivity (gluetun lowercases everything inputted, but keeps servers data text with case sensitivity). My apologies for the delay fixing it, obviously, and thank you for reporting the issue 🎖️ 

Just in case you are not aware, you can use released docker images such as `qmcgaw/gluetun:v3` or `qmcgaw/gluetun:v3.34.1` which should be more stable than the latest image `qmcgaw/gluetun`. I always appreciate users using the latest image since this helps fix bugs before bringing them to a stable release which would end up unstable, so ideally keep using the latest image 😉

**Comment by qdm12** [comment]
PS: thanks @Fastjur for pointing out the duplicate 👍
