### ISSUE TITLE
[Feature request]: Socks5 Proxy without openvpn

### ISSUE THREAD

**Issue by engageub** [qdm12/gluetun#1724]
### What's the feature 🧐

Hi,
Is it possible to use socks5 server having using username and password to create a VPN and then use this through network=container:<container_name> .
I would like to create a VPN using socks5 servers without using ovpn config.
I am already using tun2socks but there is an existing issue with UDP, so would like to know if this can compensate what tun2socks does already. 
It would basically be a VPN without any certificates in config file if it is implemented. 

Thank you

### Extra information and references

Reference: https://github.com/xjasonlyu/tun2socks

**Comment by qdm12** [comment]
You can already use shadowsocks which is a socks5 proxy with encryption on top. Note it's its own protocol, not a socks5 proxy server. See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-lan-device-to-gluetun.md#shadowsocks-proxy

If you want a socks5 proxy server (without encryption) subscribe to issue #234 although it's not a priority really, since Shadowsocks is clearly the superior option (except for devices like TV where you can't install apps).

**Comment by timdonovanuk** [comment]
"except for devices like TV", and browsers without plugins, and the entire *arr stack, and phones and and and....
