### ISSUE TITLE
Feature request: Map dynamic external port to static internal port

### ISSUE THREAD

**Issue by Emiliaaah** [qdm12/gluetun#1748]
### What's the feature 🧐

It would be awesome if there was an option to use port mapping to port the dynamic external port to a designated internal port. For my use case that would help immensely, since I wouldn't have to run a cronjob to update the exposed port in the application I want to expose. Which in my opinion is really ugly and can cause the ports to get out of sync for a period of time (depending on how often you run the cronjob).

I'd imagine this would look something like when you use NAT to map a specific external port to an internal port, except that this would map the dynamic external port to a static internal one.

For my use case this would only apply to protonvpn but I'd imagine this could be useful for other providers as well.

**Comment by qdm12** [comment]
Done in https://github.com/qdm12/gluetun/commit/4105f74ce19faab30ce0c7758745b7d0751ad08e with `VPN_PORT_FORWARDING_LISTENING_PORT`

Note for example for torrenting applications, this doesn't help really since you need to update the "VPN server side" port exposed in your torrent settings to announce to peers on which port to connect through the VPN server ip. We have no control on the VPN server firewall/redirections.
