### ISSUE TITLE
Bug: Gluetun may break host networking

### ISSUE THREAD

**Issue by jmaximusix** [qdm12/gluetun#1765]
### Is this urgent?

Yes

### Host OS

Arch Linux

### CPU arch

x86_64

### VPN service provider

Windscribe

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2023-07-22T16:07:05.641Z (commit eecfb39)

### What's the problem 🤔

After working without any issues for a few hours (sometimes even an entire day) it always breaks in the same way:

(see logs)

As far as I can tell this happens pretty much out of nowhere. I then fails to ever re-establish the connection and is trapped in a loop of restarting. It also breaks network connectivity on the host, which I thought shouldn't even be possible, but excuse my ignorance here. I was unable to ssh connect to it (it's on my local network) until manually hard rebooting the machine.

Any help would be greatly appreciated!

### Share your logs

```plain text
2023-07-27T07:26:35Z INFO [healthcheck] unhealthy: dialing: dial tcp4 xx.xx.xx.xx:xx:443: i/o timeout
2023-07-27T07:26:43Z INFO [healthcheck] program has been unhealthy for 6s: restarting VPN (see https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md)
2023-07-27T07:26:43Z INFO [vpn] stopping
2023-07-27T07:26:45Z INFO [vpn] starting
2023-07-27T07:26:45Z INFO [firewall] allowing VPN connection...
2023-07-27T07:26:45Z INFO [openvpn] OpenVPN 2.5.8 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Nov  2 2022
2023-07-27T07:26:45Z INFO [openvpn] library versions: OpenSSL 3.1.1 30 May 2023, LZO 2.10
2023-07-27T07:26:45Z INFO [openvpn] TCP/UDP: Preserving recently used remote address: [AF_INET]xx.xx.xx.xx:xx
2023-07-27T07:26:45Z INFO [openvpn] UDP link local: (not bound)
2023-07-27T07:26:45Z INFO [openvpn] UDP link remote: [AF_INET]xx.xx.xx.xx:xx
2023-07-27T07:26:56Z INFO [healthcheck] program has been unhealthy for 11s: restarting VPN (see https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md)
2023-07-27T07:26:56Z INFO [vpn] stopping
2023-07-27T07:26:56Z INFO [vpn] starting
2023-07-27T07:26:56Z INFO [firewall] allowing VPN connection...
2023-07-27T07:26:56Z INFO [openvpn] OpenVPN 2.5.8 x86_64-alpine-linux-musl [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Nov  2 2022
2023-07-27T07:26:56Z INFO [openvpn] library versions: OpenSSL 3.1.1 30 May 2023, LZO 2.10
2023-07-27T07:26:56Z INFO [openvpn] TCP/UDP: Preserving recently used remote address: [AF_INET]xx.xx.xx.xx:xx
2023-07-27T07:26:56Z INFO [openvpn] UDP link local: (not bound)
2023-07-27T07:26:56Z INFO [openvpn] UDP link remote: [AF_INET]xx.xx.xx.xx:xx
2023-07-27T07:27:12Z INFO [healthcheck] program has been unhealthy for 16s: restarting VPN (see https://github.com/qdm12/gluetun-wiki/blob/main/faq/healthcheck.md)
2023-07-27T07:27:12Z INFO [vpn] stopping
2023-07-27T07:27:12Z INFO [vpn] starting
```
(wasn't sure if it's best to replace the ip adresses, I'm sorry if that's stupid / unneccessary)
```


### Share your configuration

```yml
This is the part in my docker compose file:

services:
  vpn:
    image: qmcgaw/gluetun
    container_name: vpn
    cap_add:
      - NET_ADMIN
    environment:
      - UPDATER_PERIOD = 24h
      - VPN_SERVICE_PROVIDER=windscribe
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${OPENVPN_USER:?Missing OpenVPN Username}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD:?Missing OpenVPN Password}
      - SERVER_REGIONS=Germany
    networks:
      - my_network
    ports:
      # passed through some ports for apps that connect to it here
    restart: unless-stopped
```

**Comment by jmaximusix** [comment]
I‘d like to add I of course can‘t entirely rule out the possibility that my server maybe looses network connection for a few seconds every once in a while, however I‘d expect the VPN to not entirely break when that happens. Also it‘s highly unlikely that the issue is entirely the hosts fault, since with no other changes to the system, when turning off my docker containers, my network has never broken entirely in months, however I‘m still confused, but why the container can even affect the host that way. If anyone has recommendations on how to further troubleshoot this please let me know :D

**Comment by aidengaripoli** [comment]
I had this same problem but I managed to fix it by re-generating my VPN provider's configuration and updating the values provided to gluetun. I'm using Wireguard with TorGaurd. I think TorGuard's addresses may have changed 🤷‍♂️

**Comment by jmaximusix** [comment]
Thanks for your reply. However since I only use my credentials and no configuration file from windscribe they stay the same and I can’t regenerate them. (I could generate an .ovpn file but I don’t know how to use it that with glueton?)

Did you also have that same issue with your host network breaking or only the container?
Because that’s still the strangest thing about the whole thing to me

**Comment by qdm12** [comment]
How is your docker network `my_network` configured? Is it bridged? Gluetun should not affect your host network as far as I know, if it's in a bridged Docker network. Unless the docker network is not bridged or you use a funny unstable Docker setup 🤔 

Next time this happens, can you try accessing your machine with a keyboard + screen (so no network involved) so you can check what's wrong with the host network? Maybe it does get disconnected for another reason than Gluetun. You can check `iptables -nvL`, `ip route`, `ip a`

> then fails to ever re-establish the connection and is trapped in a loop of restarting

That's expected, it will keep on retrying to connect if it cannot establish the connection to the vpn server.

> I could generate an .ovpn file

Do you mind copy pasting a generated config file to see if things changed since last time? The configuration is generated by Gluetun with [this code](https://github.com/qdm12/gluetun/blob/39ae57f49d2b8175a8f12535bba0a857ed914340/internal/provider/windscribe/openvpnconf.go#L12). Maybe values changed, although that would only affect Gluetun connecting to the vpn server and nothing else.

**Comment by jmaximusix** [comment]
Hey, thanks for the reply.
I did some digging now that it happened again and found that it was connected to this kernel message:
```
Jul 27 09:26:43 jserver kernel: NETDEV WATCHDOG: enp1s0 (r8169): transmit queue 0 timed out 9174 ms
```
I compared it to the logs above (Note: you have to add 2 hours to those, since they're in UTC and my kernel logs in my local TZ) and noticed, that the VPN container detected being unhealthy **before** the error message in the kernel appears. However I'm not entirely sure whether this can be taken as 100% proof, since I don't know if the logs are exactly synchronized.

Digging through my `journalctl` history in over 6 months this kernel message only ever appeared in the last week, precisely since I also have this docker setup. This is the reason it lead me to believe it's the containers fault. But now I think the kernel actually might have been at fault here, and the time it first occurred due to an unfortunate kernel update and the time I tried your container might just have coincided. I'll obviously keep an eye on it but would consider it closed for now.
Sorry for misdiagnosing it as an issue of your container.

**Comment by dimitur2204** [comment]
Hello,

I am not sure this issue is the exact same problem I am having, but they seem related.

I encountered the issue while experimenting with the ports configuration. I had a large list of ports defined for exposure and decided to test `network_mode: host` as a potential shortcut. Unfortunately after I did it I suspect Gluetun's firewall started now blocking incoming connections on the host.

All services publicly exposed through Nginx/Cloudflare, as well as those I access via Tailscale, are no longer reachable. SSH access is also failing. Interestingly when attempting to SSH through Tailscale, I receive an `Operation timed out error` and direct SSH attempts result in a `Connection reset by peer error`, although this might be port 22 not being exposed on my router.

Any insights or suggestions on how to restore connectivity would be greatly appreciated.

**Comment by jmaximusix** [comment]
I think they're not the same issue. Also, mine did go away a few days later with a kernel patch so I really think mine was due to a bad kernel version that introduced this issue.

Apart from that, I'm not entirely sure whether in your case that might even be intended behaviour?
I've never used it in host networking mode, therefore I'm unsure about it.
What are you trying to achieve?
If you want to route the whole traffic of your machine through s VPN why even use a docker container for it?
Otherwise, why not use a bridge network?
Also I think maybe it would work if you manually allow all the open ports through the gluetub firewall
