### ISSUE TITLE
Bug: -privateinternetaccess doesn't work to list PIA servers, despite documentation saying so

### ISSUE THREAD

**Issue by jathek** [qdm12/gluetun#1828]
### Is this urgent?

No

### Host OS

6.1.38-Unraid/Slackware 15.0

### CPU arch

x86_64

### VPN service provider

Private Internet Access

### What are you using to run the container

docker run

### What is the version of Gluetun

Running version v3.35.0 built on 2023-06-28T13:06:38.000Z (commit 44bc60b)

### What's the problem 🤔

[Documentation](https://github.com/qdm12/gluetun-wiki/blob/main/setup/servers.md#list-of-vpn-servers) says to run `docker run --rm -v /tmp:/gluetun ghcr.io/qdm12/gluetun:v3 format-servers -privateinternetaccess` to list servers. The CLI returns `-private internet access` as the flag to use. This works, but only when used as `-private\ internet\ access`. 

### Share your logs

```plain text
flag provided but not defined: -privateinternetaccess
Usage of markdown:
[...]
  -private internet access
        Format Private Internet Access servers
```

### Share your configuration

```yml
not relevant
```

**Comment by qdm12** [comment]
Thanks for reporting this!! I did not foresee this at all, I changed it to be with dashes instead of spaces so it's less cumbersome to use. This is true on the latest image (+future release v3.36.0), since commit 6aa4a93665563e4aa30491c6fe5d2a4946fb6699

I'll update the wiki and close the issue once I make that v3.36.0 release 😉

**Comment by malhovic** [comment]
@qdm12 We're also running into issues when you try to run the updater: 
`panic: provider private-internet-access not found in hardcoded servers map; did you add the provider key in the embedded servers.json?`

I dug through and can see the git version of that doc but I can't seem to run the built-in updater. I'm only posting this on top of this issue because I have a feeling they're linked.
