### ISSUE TITLE
Feature request: intermediate release

### ISSUE THREAD

**Issue by Marsu31** [qdm12/gluetun#1920]
### What's the feature 🧐

Hi !

Could you please publish an intermediate release containing at least vpn port forwarding ?
I use Truenas scale and it integrates v3.35 (commit 44bc60b) which has not this feature. The Truenas team won't upgrade if there is no new release and I (and other ProtonVPN + port forwarding users) can't enjoy VPN benefits.

Regards

**Comment by qdm12** [comment]
Done as v3.36.0 😉  Sorry that was long overdue but blocked by a few issues. Unfortunately, it seems protonvpn port forwarding is not so stable and can disconnect after a few hours. This seems to not be due to Gluetun's implementation of the natpmp protocol, since it also fails running the client `natpmpc` as instructed on their website. Worth a try, maybe they'll fix it soon on their end.

**Comment by Marsu31** [comment]
Thank you for your work. 🙏
