### ISSUE TITLE
Connect to a specific Windscribe server

### ISSUE THREAD

**Issue by udithap** [qdm12/gluetun#197]
1. What's the feature? Rather than connecting to a country, add the option to connect to a specific Windscribe server. For example UK has 4 servers - London Crumpets, London Tea, London Biscuits, Manchester United. USA has many more. At present I can only connect to a generic UK server. I tried and failed to specify an IP address in the OPENVPN_TARGET_IP property, as it may be that Windscribe changes this frequently.

2. Why do you need this feature? In a large country like USA, if you appear to be connecting from different locations every time, some services may get suspicious and ban you.

3. Extra information? I have seen other solutions that allow this by connecting to a specific server name, therefore it should be very much possible.

**Comment by qdm12** [comment]
For now I basically map Windscribe subdomains to a list of ip addresses that I resolve.

For example `us-east.windscribe.com` (😉 😉) maps to `23.82.8.143`, ...

I believe I extracted all those subdomains from their openvpn configuration files.

If you can find me the Windscribe subdomains for specific cities / finer geographical areas (or even better just the ip addresses) I can do it. Otherwise that would take me hours and hours to extract each address manually from each city/place and I don't have the luxury (yet 😄) to spend time doing that.

**Comment by udithap** [comment]
I wonder whether you can address this by one of the following methods without much change to the code.
a) substituting OPENVPN_TARGET_IP property with OPENVPN_TARGET_SERVER
b) let the user save the specific .opvn configuration file locally, and the script pulls the necessary information from there.

**Comment by qdm12** [comment]
1. I could allow OPENVPN_TARGET_IP to override the region settings instead of being an additional filter. But still, I'm trying to restrict user input space to keep it simple. Because you would then have to be able to also specify the port etc, going to 2) really. 
2. That's looks like a lot of headaches :smile: Especially since the life cycles of a bunch of things revolve around openvpn state.

Maybe just send me the ovpn file for a particular city/region I can have a look at the structure. For example, for Cyberghost, I DNS scanned all the country codes (from wikipedia) with their domain name to get a list of all their hostnames. Maybe there is a way to do so with Windscribe too.

**Comment by udithap** [comment]
Here it is. I removed parts of the key as I don't know whether it should appear in a public forum. The file extension should be .ovpn. My notepad added the txt.
[Github_Windscribe-London-Crumpets.ovpn.txt](https://github.com/qdm12/private-internet-access-docker/files/4925732/Github_Windscribe-London-Crumpets.ovpn.txt)

**Comment by qdm12** [comment]
Nice, thanks. It's just `<key>` blocks that are private, these are public certificates so no worry :wink: But better safe than sorry!

So in this case it's `lhr-171.whiskergalaxy.com` (no idea why it's not windscribe.com as well). Do you perhaps have a way to batch download the openvpn files? I'll look more into it tonight.

**Comment by qdm12** [comment]
Otherwise just let me know what (region+city <-> subdomain) paris you would added and I can manually add them

**Comment by qdm12** [comment]
I sent an email to Windscribe support to know if they have a way (ideally an API endpoint) to obtain data for their servers such as their hostname and region. I'll let you know when I get an answer.

**Comment by qdm12** [comment]
From their support:

> Sure, you can use this URL: https://assets.windscribe.com/serverlist/mob-v2/1/123456789

> The last part (123456789) is a cache breaker. Set that to current unix time. This list doesn't return all servers at all times, but it will return at least 1 server in all connectible locations. 

> For your purposes ip2 = address of the openvpn listener. ip3 is used for Wireguard.

I'll update the updating mechanism for windscribe to use these, and see if I can add their hostnames to the data model so that you can specify some hostnames to use as a server filter. I'll close the issue once done.

**Comment by qdm12** [comment]
Hello @udithap can you please try `qmcgaw/private-internet-access:windscribe-api` using the `HOSTNAME` environment variable? You can now optionally filter servers you want to use with the environment variables `REGION`, `CITY` and `HOSTNAME` (you can also specify multiple values for each at the same time by separating values with commas).

Let me know if it works for you and I'll merge it with the main Docker image. Thanks for your patience!
