### ISSUE TITLE
Feature request: Ability to add custom OpenVPN servers instead of just pre-baked providers

### ISSUE THREAD

**Issue by thefunkygibbon** [qdm12/gluetun#207]
1. What's the feature?
as title

2. Why do you need this feature?
because not everyone has the providers listed

3. Extra information?
nope

**Comment by qdm12** [comment]
Hello, thanks for creating your first issue 👍 
Although that seems straight forward, because of the way the program is architectured, it might be actually a bit tedious to do that. I will keep it opened but I most likely won't be able to implement it soon. I'll ping back on this issue once it moves ahead.

**Comment by qdm12** [comment]
If you need another provider, please create an issue and I'll add it to the list of providers.

For support for a custom openvpn configuration file, let's refer to #223.

**Comment by qdm12** [comment]
See https://github.com/qdm12/gluetun/issues/223#issuecomment-791994363
