### ISSUE TITLE
Privado zip download timeout is too short

### ISSUE THREAD

**Issue by Drmachinegun** [qdm12/gluetun#2223]
### What's the feature 🧐

Include the option to update the VPN server list from a local .zip

### Extra information and references

Im trying to update the privado server list and it times out trying to connect. i copied the output from the update command in to my browser and downloaded the same .zip it was trying to download.
It would be great if i could tell the command to use this zip instead of it trying to go get it
something like this i guess
```update-local /pathtozip/ -providers provider.```
thanks for you time to make this its been great

**Comment by qdm12** [comment]
The client timeout is set to 10 seconds, how long does the download take for you?? For me it's near instantaneous.
I'm rather short on time and this doesn't seem like a high priority issue, so I would ideally just fix the timeout in the code and close this issue, since I may never find the time to implement such feature.

**Comment by Drmachinegun** [comment]
It probably takes 10 seconds or so to timeout, I'll find out how to adjust the timer, or maybe learn how to implement the feature myself, sounds fun.
 thanks for taking the time to create this

**Comment by qdm12** [comment]
> I'll find out how to adjust the timer, or maybe learn how to implement the feature myself, sounds fun.

I would go against loading data from a zip file, since not all VPN providers give a zip file. It feels it would introduce unneeded complexity and long term support. Also, it's strange it takes > 10 seconds to download that zip file, is your internet bandwidth very slow (check on fast.com) or internet latency very high? The zip file is 600KB, it should download within 10 seconds in pretty much all cases I can think of, except if you run internet infrastructure from the 90s 🤔

**Comment by Drmachinegun** [comment]
Internet infrastructure and speed is fine, I got it up and working using slickvpn but it expires next month, only privado gives me problems. I'll adjust the timer when I get around to messing with it again. Thanks again for your time

**Comment by qdm12** [comment]
Ok thanks for letting me know, closing this for now.
