### ISSUE TITLE
Feature Request: control server authentication

### ISSUE THREAD

**Issue by smerschjohann** [qdm12/gluetun#2238]
### Is this urgent?

No

### Host OS

Fedora CoreOS

### CPU arch

x86_64

### VPN service provider

Custom

### What are you using to run the container

docker run

### What is the version of Gluetun

Running version v3.38.0 built on 2024-03-25T15:53:33.983Z (commit b3ceece)

### What's the problem 🤔

The internal service exposes its complete configuration to unauthenticated local services and users. It is also possible to change the state of the VPN by restarting the VPN (and maybe other things).

A basic protection using an Authorization Header would be good to ensure no thirdparty that might know of the presence of gluetun can gain the VPN credentials.
Otherwise it's nice to have the API.

### Share your logs (at least 10 lines)

```plain text
# curl http://localhost:8000/v1/vpn/settings

{"type":"wireguard","provider":{"name":"*******","server_selection":{"vpn":"wireguard","target_ip":"0.0.0.0","countries":["********"],"categories":null,"regions":[],"cities":null,"isps":null,"names":null,"numbers":null,"hostnames":null,"owned_only":false,"free_only":false,"premium_only":false,"stream_only":false,"multi_hop_only":false,"port_forward_only":false,"openvpn":{"config_file_path":"","tcp":false,"custom_port":0,"pia_encryption_preset":""},"wireguard":{"endpoint_ip":"0.0.0.0","endpoint_port":0,"public_key":""}},"port_forwarding":{"enabled":false,"provider":"","status_file_path":"/tmp/gluetun/forwarded_port","listening_port":0}},"openvpn":{"version":"2.5","user":"","password":"","config_file_path":"","ciphers":null,"auth":"","cert":"","key":"","encrypted_key":"","key_passphrase":"","pia_encryption_preset":"","mssfix":0,"interface":"tun0","process_user":"nonrootuser","verbosity":1,"flags":null},"wireguard":{"private_key":"*************************","pre_shared_key":"","addresses":["10.5.0.2/32"],"allowed_ips":["0.0.0.0/0","::/0"],"interface":"tun0","mtu":1400,"implementation":"auto"}}

---
curl -X PUT --data '{ "status": "stopped"}' http://localhost:8000/v1/vpn/status
{"outcome":"stopped"}
```

**Comment by qdm12** [comment]
Please change your issue title to a Feature request since this isn't a bug, and it isn't urgent. In the meantime, you can do one of the following:

- setup an http proxy with authentication in front of the gluetun control server to achieve this
- not publish the port of the server
- add host firewall rules to restrict which ip address has access to it

**Comment by smerschjohann** [comment]
Thanks for the feedback. Sure, I changed it accordingly. I was not really sure how to classify it myself. It reallly depends on how you use the gluetun. But yes, agreed, changed.

Depending on the setup a firewall won't be easily achievable, especially if you use it as a sidecar. But for all that might expose the port currently, I second your suggestions.

**Comment by qdm12** [comment]
@ezekieldas you are totally right. It was not documented since - especially patching settings on the /v1/vpn endpoint - might be rather unstable, so I did not want people jumping on relying on this feature. I did not foresee this as a security hole, but it can be indeed! Warning documented in https://github.com/qdm12/gluetun-wiki/commit/b5601b7a44da66cc5b9123498cabfe5849636a03

Now back to authentication, I've added an [authentication section](https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/control-server.md#authentication) in https://github.com/qdm12/gluetun-wiki/commit/af0f87c5452eba7ad4e1e3d07dac798bb4e8a681 

1. I don't think we really need a global authentication built-in Gluetun, a reverse proxy would handle this better.
2. `HTTP_CONTROL_SERVER_DISABLE_SETTINGS` would do the trick for people aware of it; I would rather document it as a warning, and fix it for good soon ™️ (see below). It also opens the door for many other DISABLE settings, and extra logic that would have to stay to maintain retro-compatibility (sorry I'm obsessed with retro-compatibility 😄)
3. In a v4.0.0 Gluetun (added to #1113), there should be roles with access to specific routes, using basic auth, and no access by default. For example qbittorrent user with password abcde can only access `/v1/vpn/portforwarded`, nothing else.
4. Now, to avoid breaking compatibility, should we keep insane defaults where all existing routes are publicly accessible by default 🤔?
5. If we keep the default no-authentication as it is, we could still have the same code as described in 2. except that it would create a `public` role by default with access to the existing (documented) routes (not undocumented or future ones).

Any thoughts on these few points?

Now I went ahead to throw some ideas for implementing 4. feel free to add ideas/criticize etc.:

- we would need a structured auth config file, an environment variable won't cut it for this.
- Config file format Toml could be nice to use for newbies, any other suggestion? Or stick to json?
- add an environment variable `HTTP_CONTROL_SERVER_AUTH_FILEPATH`
- Toml file would look like:

    ```toml
    # Authentication for Gluetun's control server
    [roles]
    [roles.public]
    auth = "none"
    routes = ["GET /v1/openvpn/status", "PUT /v1/openvpn/status"] # more routes to add
    ```

- We can start by just supporting basic auth for all routes for the time being.

**Comment by joejose97** [comment]
From a security perspective, my thoughts on the api are as follows
1. It's exposed on the local network.
   - In case of ipvlan/macvlan networks, there is no way to protect the api other than to have some auth within gluetun.
   - In other types of networks, we can stick a reverse proxy in front.
2. In cases where other containers are using gluetun's networking stack, all the other apps can send request to localhost:8000 to reach it
   - This works well for easy control but we should at least protect the /settings route.
   - If one of the containers is malicious/was compromised by RCE, it can now steal our vpn credentials. (eg: the RCE in qbittorrent https://github.com/qbittorrent/qBittorrent/issues/18731)

To deal with both 1 & 2, I think we need some kind of auth in gluetun.
Both are not severe issues, but issues nonetheless.

**Comment by joejose97** [comment]
> @ezekieldas you are totally right. It was not documented since - especially patching settings on the /v1/vpn endpoint - might be rather unstable, so I did not want people jumping on relying on this feature. I did not foresee this as a security hole, but it can be indeed! Warning documented in [qdm12/gluetun-wiki@b5601b7](https://github.com/qdm12/gluetun-wiki/commit/b5601b7a44da66cc5b9123498cabfe5849636a03)
> 
> Now back to authentication, I've added an [authentication section](https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/control-server.md#authentication) in [qdm12/gluetun-wiki@af0f87c](https://github.com/qdm12/gluetun-wiki/commit/af0f87c5452eba7ad4e1e3d07dac798bb4e8a681)
> 
>     1. I don't think we really need a global authentication built-in Gluetun, a reverse proxy would handle this better.
> 
>     2. `HTTP_CONTROL_SERVER_DISABLE_SETTINGS` would do the trick for people aware of it; I would rather document it as a warning, and fix it for good soon ™️ (see below). It also opens the door for many other DISABLE settings, and extra logic that would have to stay to maintain retro-compatibility (sorry I'm obsessed with retro-compatibility 😄)
> 
>     3. In a v4.0.0 Gluetun (added to [v4.0.0 Gluetun #1113](https://github.com/qdm12/gluetun/issues/1113)), there should be roles with access to specific routes, using basic auth, and no access by default. For example qbittorrent user with password abcde can only access `/v1/vpn/portforwarded`, nothing else.
> 
>     4. Now, to avoid breaking compatibility, should we keep insane defaults where all existing routes are publicly accessible by default 🤔?
> 
>     5. If we keep the default no-authentication as it is, we could still have the same code as described in 2. except that it would create a `public` role by default with access to the existing (documented) routes (not undocumented or future ones).
> 
> 
> Any thoughts on these few points?
> 
> Now I went ahead to throw some ideas for implementing 4. feel free to add ideas/criticize etc.:
> 
>     * We can start by just supporting basic auth for all routes for the time being.
> 
>     * An auth http middleware would be nice to handle all this, instead of adding an if block per route.
> 
>     * we would need a structured auth config file, an environment variable won't cut it for this.
> 
>     * Config file format Toml could be nice to use for newbies, any other suggestion? Or stick to json?
> 
>     * add an environment variable `HTTP_CONTROL_SERVER_AUTH_FILEPATH`
> 
>     * Toml file would look like:
>       ```toml
>       # Authentication for Gluetun's control server
>       [roles]
>       [roles.public]
>       auth = "none"
>       routes = ["GET /v1/openvpn/status", "PUT /v1/openvpn/status"] # more routes to add
>       ```

1. I think we need some auth regardless. (see above comment)
2. This would be nice to have.
3. This is also nice to have, but is this worth the effort? Seems like a niche usecase.
4. I want to have auth globally, with an auto generated password at startup if default settings are not changed.
   - ie let's say we ship with env defaults as user:gluetun pass:"", if we see this we autogenerate a random password at startup. If user/pass is changed to something else, we accept user settings.
   - But to reduce breakage for existing users, we can probably secure just the sensitive routes.
5. I think having no auth at all will have the issues described in the above comment.


For v4
1. I think basic auth globally might be sufficient for our use cases.
2. Yes, this is nice to have but I'm not sure if the added complexity is worth it.

**Comment by smerschjohann** [comment]
I second that the default should be with authentication, you could introduce a setting that allows removal, if you think that should be available as well. everyone that relies on it because of scripts/software that can not be changed directly, would have a chance to use that flag before securing their endpoint.

As you mentioned in your earlier statements, the endpoints weren't documented as you did not want them to be used for now. So the amount of users that use them should be rather small. In addition, when the users updating the software, it can be quite visible that a password is set, so everyone that uses it can become aware quite easily (in addition to a 401).

I would be fine with a simple basic authentication, a sophisticated role model is not required. At most a view and edit role might become handy.

**Comment by qdm12** [comment]
How about, chronologically:

1. All **documented** routes stay publicly accessibly EXCEPT the GET /settings paths by default (for security reasons, it's worth breaking compatibility for that one).
2. When a request is received to an existing+documented http handler without authentication, log a warning stating the v3.41.0 release (4 to 6 months away) will require authentication for that route and give a wiki link on how to set it up already.
3. After release v3.40.0 (next one), force authentication for all routes on the master branch / latest image.

That way:

- high priority security hole is fixed now, breaking compatibility because it's really needed.
- low priority security holes are fixed gradually, starting in ~2 months and ending in ~4 months, breaking compatibility "smoothly"

> This is also nice to have, but is this worth the effort? Seems like a niche usecase.
> I would be fine with a simple basic authentication, a sophisticated role model is not required

Indeed, but having dealt with users here, there will be requests for that 😄 Especially since it's a "security-oriented" tool, with (some) security aware people. Plus you don't really want to have a container access your credentials just because it needs to know the current forwarded port or the current public ip address 😉 Having seen several gluetun-xyz containers to sync for example torrent clients, there could be a malicious one eventually (or one becoming malicious). I will sleep better too 💤 

Now regarding auth mechanisms, let's restrict to basic auth for now, with the code ready for more, that users can PR later if they want to.

> At most a view and edit role might become handy.

Since (for now) it's a REST API, GET verb requests are always only view, whereas PUT/POST are 'edit', so a per verb-route authentication does the job.

---

Since I'm pretty worried to leave this unsecured and excited to implement that authentication, @joejose97 I'm thinking I'll add the code infrastructure for authentication and what's said above, and then let you migrate your basic auth PR on top of my PR to add the first auth mechanism (basic auth), does that work for you? It should take a ~week to finish I think, starting tomorrow.

Finally a few additional questions (opinions welcome):

1. Auth configuration file default path: `/gluetun/server/auth.toml`?
2. Ok with the toml format? I think toml is nice for humans/not-super-deep-in-IT people
3. Any suggestion for different naming/additional fields in the file configuration?
4. OK with: if config file doesn't exist, create it with its default values

**Comment by joejose97** [comment]
@qdm12 Sounds good to me.
Since we have a simple config file, toml would work well with the fields you defined.
Let me know if I can be of help.

**Comment by qdm12** [comment]
Work in progress PR to add an auth middleware as described above more or less:
https://github.com/qdm12/gluetun/pull/2434
It should work but I gotta run and didn't test it or add documentation yet for the (optional) toml file syntax.
Feel free to review the code and comment with questions/suggestions/changes needed 😉

**Comment by qdm12** [comment]
I'm thinking to implement oauth 2.1 directly and skip basic auth and token based authentication (which as far as I understood can support basic auth and bearer tokens). I'll have a look first, and see how it affects the "base code" of that PR.

**Comment by Aubermean** [comment]
Oauth is overkill, a simple token is fine, and please don't remove the option of no authentication at all (if you don't need the API, don't expose the port or use the API...)

**Comment by Aubermean** [comment]
> @ezekieldas you are totally right. It was not documented since - especially patching settings on the /v1/vpn endpoint - might be rather unstable, so I did not want people jumping on relying on this feature. I did not foresee this as a security hole, but it can be indeed! Warning documented in [qdm12/gluetun-wiki@b5601b7](https://github.com/qdm12/gluetun-wiki/commit/b5601b7a44da66cc5b9123498cabfe5849636a03)
> 
> Now back to authentication, I've added an [authentication section](https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/control-server.md#authentication) in [qdm12/gluetun-wiki@af0f87c](https://github.com/qdm12/gluetun-wiki/commit/af0f87c5452eba7ad4e1e3d07dac798bb4e8a681)
> 
> 1. I don't think we really need a global authentication built-in Gluetun, a reverse proxy would handle this better.
> 2. `HTTP_CONTROL_SERVER_DISABLE_SETTINGS` would do the trick for people aware of it; I would rather document it as a warning, and fix it for good soon ™️ (see below). It also opens the door for many other DISABLE settings, and extra logic that would have to stay to maintain retro-compatibility (sorry I'm obsessed with retro-compatibility 😄)
> 3. In a v4.0.0 Gluetun (added to [v4.0.0 Gluetun #1113](https://github.com/qdm12/gluetun/issues/1113)), there should be roles with access to specific routes, using basic auth, and no access by default. For example qbittorrent user with password abcde can only access `/v1/vpn/portforwarded`, nothing else.
> 4. Now, to avoid breaking compatibility, should we keep insane defaults where all existing routes are publicly accessible by default 🤔?
> 5. If we keep the default no-authentication as it is, we could still have the same code as described in 2. except that it would create a `public` role by default with access to the existing (documented) routes (not undocumented or future ones).
> 
> Any thoughts on these few points?
> 
> Now I went ahead to throw some ideas for implementing 4. feel free to add ideas/criticize etc.:
> 
> * We can start by just supporting basic auth for all routes for the time being.
> * An auth http middleware would be nice to handle all this, instead of adding an if block per route.
> * we would need a structured auth config file, an environment variable won't cut it for this.
> * Config file format Toml could be nice to use for newbies, any other suggestion? Or stick to json?
> * add an environment variable `HTTP_CONTROL_SERVER_AUTH_FILEPATH`
> * Toml file would look like:
>   ```toml
>   # Authentication for Gluetun's control server
>   [roles]
>   [roles.public]
>   auth = "none"
>   routes = ["GET /v1/openvpn/status", "PUT /v1/openvpn/status"] # more routes to add
>   ```

Disabling the HTTP API by default, is completely fine.

Adding role based authentication is total overkill for now.

The API is documented, and it has been broken for several months for Wireguard at least. So my theory is hardly anybody uses the 'control server' feature anyway. The API not working at all on upgrade is an easy fix with documentation of the changes.

The most simple and logical conclusion would be to:

- Immediately release a version that shows nagging deprecation warnings in the logs for upcoming changes, advising to fix their image tag or be expected to make changes. Show the warnings for everyone, and for anybody actually sending requests to the API the warnings should be aggressive.
- Disable the API by default
- Change any tutorials or example code that expose the API port
- Add `API_ENABLED` boolean env var.
- Add `API_KEY` string env var, if `API_ENABLED` is true and API_KEY is blank, then fatal error at launch with `API requires authentication. Please set API key (e.g. API_KEY=y1qdXN0LWEtdGVzdC) or remove API_ENABLED=true. For more help see https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/api.md`. 
- `API_PUBLIC` or `API_OPEN` can be documented in the wiki as disabling authentication.

In addition, all changes and PR requests should:

- Make use of API versioning for major changes.
- Strictly adhere to [RESTful design principles](https://stackoverflow.blog/2020/03/02/best-practices-for-rest-api-design/).

And my personal thoughts:

- Change the name 'control server' to 'API', because it makes more sense.
- A crude way of implementing some level of RBAC would be adding another documented env var such as `API_KEY_LIMITED` which can access everything except `settings` and other sensitive endpoints. However this is a example of arguably bad, kludgy design. But it's simple - real RBAC is overkill, and for such a feature the user should implement a HTTP Proxy.

**Comment by qdm12** [comment]
> So my theory is hardly anybody uses the 'control server' feature anyway.

I disagree, there is a whole bunch of tools/scripts interacting with it. Maybe it's 1% of users, but that's potentially still a lot of people 😄 Also a die hard fan of not breaking compatibility.

> Disabling the HTTP API by default, is completely fine.

Added to #1113 definitely should be the default. Cannot break compatibility for now though, so leaving it on by default as it was.

> Adding role based authentication is total overkill for now.

It is, although I already implemented it, I think we'll go forward with it in the end 🤷 At least it (hopefully) allow some flexibility in the future.

**Comment by qdm12** [comment]
@smerschjohann @joejose97 @Aubermean @ezekieldas 

Please try image `qmcgaw/gluetun:pr-2434` together with [this documentation](https://github.com/qdm12/gluetun-wiki/blob/auth-config/setup/advanced/control-server.md#authentication). I've tried it locally and it seems to work fine so far.

For motivated reviewers:

- The PR #2434 contains the authentication together with basic auth (credits to @joejose97), apikey and none authentication methods
- The Wiki documentation PR can be reviewed and commented at https://github.com/qdm12/gluetun-wiki/pull/95/files

**Comment by joejose97** [comment]
I've also tested all the methods with multiple roles. Works as expected. Thanks for the fabulous work @qdm12 
@ezekieldas, It'd be great to include an example in the docs.

**Comment by qdm12** [comment]
> I think it still doesn't include the github username (ie, github.com/qdm12/gluetun-wiki/).

Thanks, fixed 👍 

> where do I get / how do I create an API key for this?

My idea (perhaps wrong naming) was you could set the "api key " to anything you would like in the config.toml as described in [this](https://github.com/qdm12/gluetun-wiki/blob/auth-config/setup/advanced/control-server.md#authentication-methods). A few suggestions, what do you think:

1. should this method be renamed to something else? For example `passphrase`? (low effort)
2. should Gluetun evaluate the key strength and log a warning if it's too weak? (medium effort)
3. should I add a gluetun command for example `genkey` to generate a strong api key? (low effort) - I would prefer this over suggesting the user to use another tool such as python etc since these extra tools are not always present.

Thanks @joejose97 for also confirming it works as expected 👍

**Comment by qdm12** [comment]
I've added a `genkey` command to gluetun, which generates a 128 bit random key in base 58, which you can use with `docker run --rm qmcgaw/gluetun genkey`. Also documented in wiki now!

Everything is now merged in the master branch (both gluetun and gluetun-wiki), enjoy 👍
