### ISSUE TITLE
Feature request: disable control server

### ISSUE THREAD

**Issue by engageub** [qdm12/gluetun#2318]
### What's the feature 🧐

Option to disable the control server at start. Note this doesn't need to be changed at runtime, since disabling the control server disables controlling Gluetun at runtime.
This should be added once the code migrated to use qdm12/goservices - see local branch `control-server-disable-2318`

Original description

> Hi,
> I would like to disable internal listening ports for HTTP and ShadowSocks as I don't use them.
> Despite the default options being set to "off" for both HTTP and ShadowSocks, I have observed that the internal ports remain active, as evidenced by the output of the `sudo docker container ls` command. Given that these services are not utilized in my operational context, I believe that disabling these ports could lead to a more efficient allocation of resources.
> 
> As we rely extensively on container-to-container networking and deploy multiple instances of these containers, even minor adjustments can yield significant improvements in resource utilization and overall performance. Therefore, I am keen to explore any available options to disable these listening ports.
> 
> I would greatly appreciate your guidance on how to achieve this objective or any insights you may have regarding the best practices for optimizing our container network setup in this regard.
> 
> Thank you

**Comment by qdm12** [comment]
These are exposed ports, and there is nothing listening on them. They are defined in the Dockerfile for documentation purposes. It doesn't affect performance or security in any way. Even if you publish the port, it shouldn't affect performance, since nothing is listening at the end.

The control server (port 8000) cannot be disabled for now though, so I changed your issue to provide the option to turn it off.

**Comment by alternativ** [comment]
@qdm12, thanks for your writeup and awesome piece of software. I use macvlan to manage my containers, my gluetun instance has it's own IP in the network. In order to manage it accordingly I too would like the feature to disable the control server. I can manage it with an iptables command (`docker exec containername' iptables -I INPUT 1 -p tcp --dport 8000 -j DROP`) but after a container restart or reboot that is gone.

**Comment by qdm12** [comment]
Now that there is authentication in the control server, and that it will soon be (after v3.40.0 release) compulsory to have authentication setup for all routes, there is no point having an option to disable it really, so closing this in favor of the authentication system.

@alternativ 

> but after a container restart or reboot that is gone.

See https://github.com/qdm12/gluetun-wiki/blob/main/setup/options/firewall.md#custom-iptables-rules you can specify custom iptables rules to run.
