### ISSUE TITLE
Help: dns over tls: falling back on plaintext DNS

### ISSUE THREAD

**Issue by LordShadowen** [qdm12/gluetun#235]
This always shows up in the log "dns over tls: falling back on plaintext DNS at address 1.1.1.1".  Is this expected? Does this mean that DNS over TLS is not working?
This is logged before the VPN is up, so not sure if this is a problem or not...

1. Is this urgent?

    - [ ] Yes
    - [x] No

2. What VPN service provider are you using?

    - [x] PIA
    - [ ] Mullvad
    - [ ] Windscribe
    - [ ] Surfshark
    - [ ] Cyberghost

3. What's the version of the program?

Running version latest built on 2020-09-05T16:57:43Z (commit 797fa33)

4. What are you using to run the container?

    - [ ] Docker run
    - [x] Docker Compose
    - [ ] Kubernetes
    - [ ] Docker stack
    - [ ] Docker swarm
    - [ ] Podman
    - [ ] Other:

5. Extra information

Logs:

```log

```

Configuration file:

```yml

```

Host OS:
Synology DSM

**Comment by qdm12** [comment]
Yes this is expected. DNS over TLS requires some cryptographic files and block lists obtained from Github, and these are fetched only once the tunnel is up. Before that the plaintext DNS is used, although no DNS resolution is made until the tunnel is up. It is only used to resolve Github once after the tunnel is up to get those files.

Consequent DNS requests all go through TLS, even to update the DNS related files every 24h.

It doesn't use files in the Docker image the first time because some of the cryptographic values for DNS over TLS change every 3-6 months meaning an older Docker image version would fail resolving the first time otherwise.

Finally, I left it that way as it's just one resolution of  Github.com going to cloudflare (or other) and through the tunnel. Only your vpn provider learns that you resolve github.com when you connect. That shouldn't  have an impact privacy wise.

**Comment by LordShadowen** [comment]
Awesome - thanks for the detailed explanation.
May I suggest you had this to the wiki? It makes total sense once you explain it, but it wasn't obvious to a first time user :)
That log line may lead others to assume something is wrong...

**Comment by qdm12** [comment]
I'll change the log line 😉 Let's keep the issue opened so I don't forget to do it.
