### ISSUE TITLE
Feature request: Support WireGuard in the control server

### ISSUE THREAD

**Issue by brnlee** [qdm12/gluetun#2372]
### What's the feature 🧐

I've been using the control server to toggle off and on OpenVPN to switch VPN servers when necessary. Is it possible to support something similar for WireGuard? Thank you!

**Comment by qdm12** [comment]
https://github.com/qdm12/gluetun-wiki/commit/05ee640762d00b29a966d7a7d1090b24790bc70b updated the documentation to explain which routes work with both openvpn and wireguard. Really the route should be `/vpn/` instead of `/openvpn/`, but it's kept like this for historical reasons and because maintaining retro-compatibility is somehow a pain 😄 Closing this, knowing still there is room for improvement in the control server! 😉
