### ISSUE TITLE
Bug: we need more maintainers - this is insufficient 

### ISSUE THREAD

**Issue by johnwyles** [qdm12/gluetun#2377]
### Is this urgent?

Yes

### Host OS

Alpine

### CPU arch

x86_64

### VPN service provider

NordVPN

### What are you using to run the container

docker run

### What is the version of Gluetun

Latest

### What's the problem 🤔

tun0 unable to have perms even though dockerfile specifies - workaround arrived but I am sure many user are down after updating the image to latest

### Share your logs (at least 10 lines)

```plain text
I love what you have done for this project but it’s clearly gone beyond your scope to manage and handle PRs etc which we all discuss in the message side of things. I suggest you assign some trusted maintainers and let your project take off more than it already has but right now it is handicapped by simple errors pushed out to hundreds of thousand maybe millions of users and it’s too much of a burden to be put on you. You need to hand control over to people you trust and your name remains at the top just put some other chiefs in charge to handle the business but at it stands I have to revert to an old build and looking at your ticket log I certainly wasn’t the only one. Be smart. Love you dude and thanks but let’s work on better management of the project… you don’t owe me an update just fix your management of a great project you have and you’re all set.
```

**Comment by johnwyles** [comment]
My comments directed to you are in the “Logs” section and you should take them to note for yourself. We love the work you’ve put in but it’s time to relax the controls a bit and let others also pitch in and help you’ll find my fixes and PRs in history which shut down a lot of people using your lovely tool. Please take it to heart to find some maintainers and keep this project alive or it will be forked from here and left behind - I want you to take charge. Lead if you have the time and if you don’t (like many of us) you give controls to others you trust. Consider this. I hope you make good decisions from here - I know this project blew up on you and that’s why I beg you to look for maintainers.

**Comment by qdm12** [comment]
> tun0 unable to have perms even though dockerfile specifies - workaround arrived but I am sure many user are down after updating the image to latest

Describing this is rather useless. What does `tun0 unable to have perms` even mean?? I need more details, you don't even share the work around or any useful information. Please create another issue with required details.

> but it’s clearly gone beyond your scope to manage and handle PRs etc

I'm reviewing PRs and the ones still opened and not merged are like so for specific and very valid reasons.

> which we all discuss in the message side of things

Indeed, I don't spend much time in the repository discussions and other forums, since I focus on resolving Gluetun issues which are more pressing and for which I'm 'the man', unlike message side of things where others can help as much, if not better, than I can.

> I suggest you assign some trusted maintainers

There is no one for now with the skills and motivation to work on this project. PRs are always welcome and I review them promptly.

> let your project take off more than it already has but right now it is handicapped by simple errors pushed out to hundreds of thousand maybe millions of users and it’s too much of a burden to be put on you.
> I have to revert to an old build and looking at your ticket log I certainly wasn’t the only one.

If you want stability, stick to the `:v3` tag. Users using `:latest` are on the master branch, and risk instability (rarely too). It's not a burden for me, because if people update the latest image, and get a new error, it's on them to fallback on a v3 release image tag. It's not as if there would be no image tags. I think the "old build" you are referring to was v3.38.0 from march 2024, because the latest image has been unstable since recently, and I was fixing those before cutting a new release. The v3.38.0 image was still working fine too. There were reasons there was no new release for a 4 months.

---

Now.... on the more negative side of things, perhaps I'm paranoid (eh I'm the Gluetun maintainer after all), this issue coming from your account with no prior contribution to Gluetun, barely no contribution on Github, and with some funny lines listed below, this really sounds like the [xz-utils social engineering attack](https://tukaani.org/xz-backdoor/):

> we need more maintainers - this is insufficient
> You need to hand control over to people you trust and your name remains at the top just put some other chiefs in charge to handle the business
> Be smart. Love you dude and thanks but let’s work on better management of the project… you don’t owe me an update just fix your management of a great project you have and you’re all set.
> it’s time to relax the controls a bit and let others also pitch in and help you’ll find my fixes and PRs in history which shut down a lot of people using your lovely tool.
> I hope you make good decisions from here - I know this project blew up on you and that’s why I beg you to look for maintainers.
> Lead if you have the time and if you don’t (like many of us) you give controls to others you trust

Finally, if anyone wants to fork it please go ahead. It's MIT license, do whatever you want with it. It's already forked 343 times 🤷 

> keep this project alive or it will be forked from here and left behind

Closing this for obvious reasons.
