### ISSUE TITLE
Feature request: Periodic server change (country, city)

### ISSUE THREAD

**Issue by smlylve** [qdm12/gluetun#2620]
### What's the feature 🧐

Hi, im on mullvad using gluetun.
I dont see to find any method to change server dynamically.
Any ideas, solutions? I doubt that no one has tried that yet.
I cant see to have PUT route with settings endpoint.
Best regards
smiley

**Comment by qdm12** [comment]
> I dont see to find any method to change server dynamically.

There is none built-in, subscribe to #2233 which this issue duplicates, closing this as a duplicate issue

> Any ideas, solutions? I doubt that no one has tried that yet.
> I cant see to have PUT route with settings endpoint.

Indeed, you could use that and have something interact with the control server. It's not documented because it:

- might change in the future (no compatibility promise)
- may be unstable - rebooting the internal vpn loop is not super battle tested; it works well so far, but I didn't test it to the max either
