### ISSUE TITLE
What's the purpose of -v yourpath:/gluetun?

### ISSUE THREAD

**Issue by Peppershaker** [qdm12/gluetun#340]
**Host OS** (approximate answer is fine too): Ubuntu 18
Windows WSL 2
**Is this urgent?**: No

**What VPN provider are you using**:
Nordvpn
**What is the version of the program** (See the line at the top of your logs)
latest
```
Running version latest built on 2020-03-13T01:30:06Z (commit d0f678c)
```

**What's the problem** 🤔
trying to connect to shadowsocks but not working. I'm thinking this might have to do with me commenting out the directory mounting -v yourpath:/gluetun as I'm not sure exactly what I should be mounting.

`localhost:8000` gives `unversioned API: requested URI not found`

The VPN is connected correctly inside the container, as confirmed with `docker run --rm --network=container:gluetun alpine:3.12 wget -qO- https://ipinfo.io`

**Comment by Peppershaker** [comment]
found the proxy documentation got the http proxy working. both the proxy and shadowsocks are off by default and needs to be enabled. However I couldn't get auth to work, but that is prob a problem with my setup.

**Comment by qdm12** [comment]
Hey Peppershaker!

- API is at /v1 have a look at the Github wiki
- Gluetun directory holds the servers information servers.json which you can update yourself (check the wiki) if you want to, instead of pulling a newer Docker image. It may hold other things like your PIA port forwarding token from the top of my head.
- Yes check the env variables wiki page to enable shadowsocks and the http proxy
- What auth is not working? Shadowsocks or the HTTP proxy? Chrome doesn't support auth on http proxy you would need firefox. But let me know if it doesn't work please as it may be an error on the program side for the http proxy.

**Comment by Peppershaker** [comment]
Hey, first of all thanks for all the work you put in. I tried a few other solutions before and not being an expert in networking and docker, it has been an uphill battle.

I would have to test HTTP proxy authentication more later today and let you know. I tried using the proxy with python's requests module, which allows proxying requests. The unauthenticated requests work for both HTTP and HTTPS, but no luck with password authentication. Username and password was passed in as env vars in the `docker-compose.yml`

Thanks again
