### ISSUE TITLE
Privado  server hostnames invalid

### ISSUE THREAD

**Issue by shuntera** [qdm12/gluetun#443]
I'm seeing this in my docker-compose logs for gluetun using the Privado VPN service, so the service does not start

2021/05/08 01:30:23 ERROR environment variable "SERVER_HOSTNAME": invalid values found: value "jfk-004.vpn.privado.io" at position 2, value "jfk-001.vpn.privado.io" at position 3: possible values are: akl-004.vpn.privado.io, akl-005.vpn.privado.io, ams-011.vpn.privado.io, ams-012.vpn.privado.io, (the rest deleted)

**Comment by shuntera** [comment]
Looks like the servers I had configured such as jfk-001.vpn.privado.io are not in your allowable list.  I chose from those you did have and am working now.

Any reason why you excluded them in the latest build, do they no longer exist?

**Comment by qdm12** [comment]
Reasons:

- I recently reworked the code to resolve server hostnames when updating the server information for all vpn providers and hence updated all the information too.
- The actual reason is that Privado removed the hostname you were using from their zip file at https://privado.io/apps/ovpn_configs.zip

Tips:

- the hardcoded list is [here](https://github.com/qdm12/gluetun/blob/master/internal/constants/privado.go#L25)

To do (don't close the issue):

- I'll add a link to each in the Wiki as the wiki table may get outdated
- I'll add other selectors such as country, region, city for each server using ipinfo.io. That way it should break less if you pull the image or update the server information yourself.

**Comment by qdm12** [comment]
Added a Wiki page on how to get up to date server information: https://github.com/qdm12/gluetun/wiki/Servers-Readme

**Comment by qdm12** [comment]
I have updated the list of servers in [the Wiki here](https://github.com/qdm12/gluetun/wiki/Privado-Servers).

From https://github.com/qdm12/gluetun/commit/14eb2fdcafeee788fd689db3a816b2baa7e2de29 you can now specify `COUNTRY`, `REGION` and `CITY` to filter servers, as mentioned in [the environment variables Wiki page](https://github.com/qdm12/gluetun/wiki/Environment-variables). This is available in `:latest` and on versions post `v3.17.0` 😉

**Comment by shuntera** [comment]
Thanks Quentin
