### ISSUE TITLE
Feature request: Set custom OpenVPN flags with environment variable

### ISSUE THREAD

**Issue by maximberezin97** [qdm12/gluetun#486]
I would like to be able to set custom OpenVPN CLI arguments.

I need to set custom `openvpn` flags such as these: https://openvpn.net/community-resources/reference-manual-for-openvpn-2-4/#scripting-and-environmental-variables which may be used to run a script after `openvpn` establishes a connection.
The binhex containers support this with a `VPN_OPTIONS` environment variable that supplements the `openvpn` CLI startup command as shown here: https://github.com/binhex/arch-int-vpn/blob/master/run/root/openvpn.sh#L29 and documented here: https://github.com/binhex/documentation/blob/master/docker/guides/vpn.md

It would be great if this container could provide the same functionality!

**Comment by qdm12** [comment]
You should be able to specify Openvpn flags with `OPENVPN_FLAGS="--flag1 --flag2"` now on the `:latest` image since commit 394abbbe352d369fb07eac9ba97d6a6f40efc9ed.

Note the openvpn configuration used is in `/etc/openvpn/target.ovpn` and that flags and exiting generated configuration may or may not conflict depending on the flag. Feel free to let me know if it works or not.

Thanks for your patience!
