### ISSUE TITLE
Help: Using Secrets on Synology without swarm

### ISSUE THREAD

**Issue by Adelscott** [qdm12/gluetun#496]
I'm trying to deploy a stack on my Synology using secrets for password and certificates for VPNSP=Cyberghost

I'm new to Docker so please be nice to me !  In fact I'm using portainer, it seemed convenient for a beginner instead of writing command lines

Problem : I don't know where to put the key and crt files to be able to use them as secrets on my compose deployment using portainer. 

Tried to activate the swarm, created the 4 secrets with Portainer and was able to see them with "docker secret ls". But then got errors because the compose content is not suitable for a swarm "Deployment error Ignoring unsupported options: cap_add, network_mode, restart ..., etc ..."

Leaved the swarm and stuck again with those secrets ...

**Comment by qdm12** [comment]
To be honest, I never really used Swarm so take my ideas with a grain of salt.

It might be first that you can't use NET_ADMIN with Swarm, so that's a deal breaker for gluetun which needs it.

With docker-compose (version 3 files), you can use secrets as show on the repository docker-compose.yml. You could also just bind mount it without using secrets at all, there is not much point anyway since gluetun reads it and writes it to the Openvpn configuration it uses anyway.

Also I've used Portainer, moved to raw docker-compose files (1 file per directory) and it's awesome. I'm using Kubernetes at my work but it's just overkill, so don't recommend it either. Docker is doing quite a bit of development on docker-compose (version 2 about to come out) so it's a good choice for ease of use and for the future as well. Portainer works well... until it doesn't when you need something more complex (maybe like gluetun?). docker-compose is more on par with the latest development.

**Comment by Adelscott** [comment]
Thank you ! Meanwhile I followed  this same advice you gave on another post, binding the files directly to /run/secrets/, and it seems to have worked (a "curl ifconfig.me" inside the container gives me an IP from the VPN) 

    volumes:
      - /volume1/docker/gluetun:/gluetun
      - /volume1/docker/gluetun/client.key:/run/secrets/client.key
      - /volume1/docker/gluetun/client.crt:/run/secrets/client.crt
      - /volume1/docker/gluetun/openvpn_user:/run/secrets/openvpn_user
      - /volume1/docker/gluetun/openvpn_password:/run/secrets/openvpn_password

**Comment by qdm12** [comment]
If I'm not mistaken you can even directly bind mount:

```sh
- /volume1/docker/gluetun:/gluetun
```

where client.crt and client.key are both in your gluetun directory.

For the username and password, you can also use the environment variables `OPENVPN_USER` and `OPENVPN_PASSWORD`.

Since all these inputs are read by gluetun and then written as files in the container, there is really no point using secret files except in particular situations. Plus gluetun takes care of unsetting sensitive variables like OPENVPN_USER at start.

Tasks for me before closing this:

1. [ ] Add a client key wiki page (for Cyberghost and VPN Unlimited)
2. [ ] Add a client certificate page (for Cyberghost)
3. [ ] Change docker-compose.yml to not use secrets by default
4. [ ] Clarify Docker secrets wiki page, interlinking it with 1 and 2.

**Comment by qdm12** [comment]
I clarified the Wiki, see https://github.com/qdm12/gluetun/wiki/Client-key and https://github.com/qdm12/gluetun/wiki/Client-certificate hopefully that helps for next user coming 😉
