### ISSUE TITLE
VPN provider support: perfect-privacy.com

### ISSUE THREAD

**Issue by Niklasthegeek** [qdm12/gluetun#582]
Would be nice if perfect-privacy.com could be added.

[TCP](https://www.perfect-privacy.com/downloads/openvpn/get?system=linux&protocol=tcp&scope=server&filetype=zip)
[UDP](https://www.perfect-privacy.com/downloads/openvpn/get?system=linux&protocol=udp&scope=server&filetype=zip)

**Comment by qdm12** [comment]
Acknowledged! It might take a few days/weeks though since there is already a queue of vpn providers I need to support.

A few additional questions in the meantime:

1. Do they support Wireguard?
2. Where did you get that zip file from?
3. Would they have a public web API with their server information? (if you know)

Thanks!

**Comment by Niklasthegeek** [comment]
1. They currently don't.
2. The Zip file can be acquired after logging in on the website though the link is public and not restricted to users. Authentication when connecting is still required.
3. I don't know of there is a Web API but the servers lists can be downloaded as JSON file

**Comment by qdm12** [comment]
Nice thanks!

2. Can you drop the zip link here please? That way gluetun can auto-update using it as its source
3. Do you have the link for that json file as well? If it's not public, feel free to just attach it it might be useful.

**Comment by Niklasthegeek** [comment]
2. TCP: https://www.perfect-privacy.com/downloads/openvpn/get?system=linux&protocol=tcp&scope=server&filetype=zip
   UDP: https://www.perfect-privacy.com/downloads/openvpn/get?system=linux&protocol=udp&scope=server&filetype=zip
   
3. TCP: https://www.perfect-privacy.com/downloads/openvpn/get?system=linux&protocol=tcp&filetype=json
    UDP: https://www.perfect-privacy.com/downloads/openvpn/get?system=linux&filetype=json

**Comment by qdm12** [comment]
Perfect! I'll get to it around tomorrow, right after I'm done with #546

**Comment by qdm12** [comment]
Can you try the image `qmcgaw/gluetun:perfectprivacy`? Just set `-e VPNSP="perfect privacy" -e OPENVPN_USER=youruser -e OPENVPN_PASSWORD=yourpassword` in your docker run command and that should do. You can specify a `-e CITY=amsterdam` if you want to. Let me know if it works for you, since I cannot really test it against their servers. Thanks for your patience!

**Comment by RagnarRipper** [comment]
Hey there,

I tried your command

`docker run -it --rm --cap-add=NET_ADMIN -e VPNSP="perfect privacy" -e OPENVPN_USER=unsername-e OPENVPN_PASSWORD=password-e CITY=amsterdam qmcgaw/gluetun:perfectprivacy `

(Put in user and password where necessary)

however, I'm quite new to docker and it seems that it's also a little different on unraid, so I wasn't sure where to put it.

I tried the "extra parameters" field as well as "post arguments"

In both cases it didn't work.

Let me know if you want me to try something else :)

**Comment by Niklasthegeek** [comment]
Hi, 
I also tried but it seems the client cant fully make the connection. I mad a log capture of the container 

[https://pastebin.com/yqThtf1z](https://pastebin.com/yqThtf1z)

Hope it helps to find the cause.

**Comment by qdm12** [comment]
First please re-pull: `docker pull qmcgaw/gluetun:perfectprivacy`

@RagnarRipper thanks for trying. I would need the Docker logs to debug why it doesn't work. Ultimately it should show `healthcheck: healthy!` once it's working. You can find these with `docker logs gluetun` (`gluetun` being the container name you assigned), you probably can find them on the Unraid UI too but I'm not sure where.

@Niklasthegeek thanks for sharing the logs. I see in the logs `OpenVPN was configured to add an IPv6 route. However, no IPv6 has been configured for tun0, therefore the route installation may fail or may not work as expected.` which is the problem here. Did you enable `OPENVPN_IPV6`? If yes, try disabling it. If not let me know I'll dig how to prevent this with `pull-filter`, although there are already

```
pull-filter ignore "route-ipv6"
pull-filter ignore "ifconfig-ipv6"
```

Which should prevent it from trying to route ipv6 🤔

**Comment by Niklasthegeek** [comment]
I tested a little more and i  did not enable ipv6
the used command is up on top of the paste 
i noticed the seemingly wrong cipher
[https://pastebin.com/uA7A0hS8](https://pastebin.com/uA7A0hS8)

after manually setting cipher 
[https://pastebin.com/QbR51Ghk](https://pastebin.com/QbR51Ghk)

**Comment by qdm12** [comment]
> i noticed the seemingly wrong cipher

Indeed, I changed the default to CBC... From all their config files, they use `cipher cipher AES-256-GCM`, ugh.

> after manually setting cipher

Yes, still that IPv6 issue. I removed `redirect-gateway def1` which might had been the OpenVPN option at fault. Can you try again by `docker pull qmcgaw/gluetun:perfectprivacy` again? Thanks!

**Comment by RagnarRipper** [comment]
Sadly, it won't even start, so probably no point in getting a log? (if one is even created)

![image](https://user-images.githubusercontent.com/90118702/132923883-4a4b49e8-e0bf-4ca7-9839-1baddd6d45b1.png)

I may be doing this wrong though. Here's what I tried

- Click on "Apps" in the unraid tab bar at the top
- Search gluetungvpn
- Start the install process
- Toggle advanced view and replace `--cap-add=NET_ADMIN --restart always` in the "extra parameters" field with the code you gave me - including my username and password.
- If, at this point, I would click on "apply" it would tell me it needs a time-zone. So I put that in as well.
- Now clicking apply tells me it needs "VPN_USER" and "VPN_PASSWORD", but that gets me thinking... there's no point in putting those in here, since in the dropdowns there are other VPNS... so I remove the VPN_SERVICE_PROVIDER and user and password, as well as "VPN_TYPE"
- click apply and what's in the screenshot is the result.

I tried all different combinations of leaving the fields in, deleting only PROVIDER but putting my user and password in and setting it to openvpn, etc. 

Never got past what is in the screenshot.

I am really sorry if I'm messing this up somehow and if anybody has some pointers, I'd really appreciate it!

**Comment by qdm12** [comment]
@RagnarRipper oh boy, thanks for trying this hard! Yeah the Unraid template is definitely lagging behind on top of that, I'm doing [pull requests there to patch it with recent changes](https://github.com/DiamondPrecisionComputing/unraid-templates/pulls). 

Anyway, don't worry about it too much. It's good you reminded me the Unraid community exists 😄 So I'll patch up variables like `VPNSP` with `perfect privacy` and so on.

**Comment by RagnarRipper** [comment]
It's the least I can do. I really appreciate you even considering going through the work of putting Perfect Privacy in.

Looking forward to more testing :)

**Comment by qdm12** [comment]
@Niklasthegeek let me know if the newer version works, I think that `redirect-gateway def1` might had been the cause since it caused trouble for another provider (cyberghost) so I commented it out back then.

**Comment by Niklasthegeek** [comment]
> @Niklasthegeek let me know if the newer version works, I think that `redirect-gateway def1` might had been the cause since it caused trouble for another provider (cyberghost) so I commented it out back then.

Sorry i have very little time this week. I will test it on the Weekend. i'll promise ;)

**Comment by qdm12** [comment]
Hey @Niklasthegeek, did you have time to test it? Thanks!

**Comment by Niklasthegeek** [comment]
> Hey @Niklasthegeek, did you have time to test it? Thanks!

Yey i tested it but it still doesn't work
[https://pastebin.com/SXLtuDwY](https://pastebin.com/SXLtuDwY)

**Comment by qdm12** [comment]
Please pull the `qmcgaw/gluetun:perfectprivacy` image and try again. I fixed it was using the wrong port number, my apologies!!

**Comment by qdm12** [comment]
Also in case `qmcgaw/gluetun:perfectprivacy` does fail with an `AUTH_FAILED` error, try `qmcgaw/gluetun:perfectprivacy-2`.

**Comment by Niklasthegeek** [comment]
i've tested again but still no success [https://pastebin.com/wrY8xtwh](https://pastebin.com/wrY8xtwh)

**Comment by RagnarRipper** [comment]
That's awesome. So how would a noob like me get this to work on unraid? (or is that something you update on your end?)

Thank you for your great work!

**Comment by qdm12** [comment]
@RagnarRipper I'll update the Unraid template as soon as @Niklasthegeek confirms it works 😉

I need to update the Unraid template for a bunch of other things too (like Wireguard) as well. I'll let you know here once it's updated.

**Comment by Niklasthegeek** [comment]
We are further but i stil cant connect AUTH_FAILED 
My credentials are perfectly fine.

[https://pastebin.com/mkd9auvW](https://pastebin.com/mkd9auvW)

**Comment by qdm12** [comment]
How about now? (pull it again) I re-removed the ignore option `pull-filter ignore "auth-token"`, that might do it.

**Comment by RagnarRipper** [comment]
Hey @qdm12 I was thinking that, if it helps, I wouldn't mind just giving you my login details for Perfect Privacy - since I can't sponsor an account. That way you can just try away?

Let me know if that's an option for you. I would share it with your email through a bitwarden link and password.

**Comment by qdm12** [comment]
@RagnarRipper yes that's a good idea, because indeed this ping pong is getting long 😄 You can send it to quentin.mcgaw@gmail.com and change your password once I'm done. It shouldn't take more than a few hours 😉

**Comment by RagnarRipper** [comment]
You've got mail :)

**Comment by qdm12** [comment]
@RagnarRipper you can change your credentials now, I tested and it works 100% now.

FYI the previous image was working, but now I managed to remove the IPv6 errors that would show in Docker.

I am changing the Unraid template now, here's a [first PR](https://github.com/DiamondPrecisionComputing/unraid-templates/pull/4). I'll do more changes today. Feel free to comment on #550 to be updated.

**Comment by qdm12** [comment]
The unraid template should support picking perfectprivacy as Vpn service provider in about 1h30 (the app store reloads files periodically).
