### ISSUE TITLE
Privado servers out of date

### ISSUE THREAD

**Issue by mattdale77** [qdm12/gluetun#757]
Out of the 8 servers for privado in the UK, 4 are accurate. All of the ones in London are wrong. There are 3 additional servers in Manchester

I tried updating them locally in servers.json but gluetun seems to overwrite the changes after I've made them so it still doesn't work properly.

Do you need me to put the details here? Or can you look them up?

**Comment by qdm12** [comment]
d6d529278e51b910afdc2166ef9a331518c9def1 should fix it

You can read up on https://github.com/qdm12/gluetun/wiki/Updating-servers if you ever need to update servers automagically.

Otherwise to manually add them, you would have to either increase the version for Privado in servers.json or increase the timestamp so it takes precedence over the program built-in data.
