### ISSUE TITLE
Wiki issue: Env Variables for WIREGUARD incorrect in Wiki 

### ISSUE THREAD

**Issue by adamchasetaylor** [qdm12/gluetun#844]
examples list

VPN_ENDPOINT_IP
VPN_ENDPOINT_PORT

should be

WIREGUARD_ENDPOINT_IP
WIREGUARD_ENDPOINT_PORT

**Comment by qdm12** [comment]
Actually these are older variables (the WIREGUARD ones). They still work due to retro-compatibility but will be ultimately dropped in a v4 release (not anytime soon). Although yes these new variables only work on the latest image, I'll make another release soon.

I guess the wiki should be versioned too 🤔

**Comment by adamchasetaylor** [comment]
Thanks for the quick response. I'll change my variables in my Docker Config file!
