### ISSUE TITLE
Wiki issue: Not clear how to specify id and password for ivpn openvpn setup

### ISSUE THREAD

**Issue by GodGoldfish** [qdm12/gluetun#856]
Hello,
Because there are two ways to login with ivpn an accurate way of how to do it would be cool.
Example :

OpenVPN SETUP
for Email :
      VPN_TYPE: "openvpn"
      OPENVPN_USER: "email@email.abc"
      OPENVPN_PASSWORD: "hereisyourpassword"

for Account ID :
      VPN_TYPE: "openvpn"
      OPENVPN_USER: "i-" # or "ivpn-"
      OPENVPN_PASSWORD: " " # a space is required since there is no password with Account ID authenfication, no password inside the string will result with an error.

**Comment by qdm12** [comment]
Hey @GodGoldfish thanks for creating the issue.

How does the account ID way works? Is `OPENVPN_USER` a string like `i-3429423423` / `ivpn-4324523423`? Or just `i-`??

If that's the case, I'll change the code to reject a set password if the user starts with `i-` or `ivpn-` and otherwise leave it as compulsory. I'll change the Wiki page too.

**Comment by GodGoldfish** [comment]
@qdm12 
it's always "i-XXXX-XXXX-XXXX" or "ivpn-XXXX-XXXX-XXXX" (the x are letters and numbers but the "-" are important because there is one each 4 letters/numbers)

**Comment by qdm12** [comment]
- this is now done in the code in 69eee345d2a2115f46300ced97b9c3e07d5ea4e0, gluetun will accept empty password when using `ivpn` and a username matching the format you precised.
- Wiki page is updated with the information: https://github.com/qdm12/gluetun/wiki/IVPN#openvpn-only

Thanks again for sharing the information!
