### ISSUE TITLE
Feature request: docker images Tag ( latest and edge ?)

### ISSUE THREAD

**Issue by leo15dev** [qdm12/gluetun#904]
### What's the feature 🧐

I think many people like me will use watchtower to automatically update the docker container. When use the`latest` label, it will consistent to the  master build, however, today, my gluetun container worked failed after watchtower to automatically update it. But, I found that there is new release `v3.28.1`, I changed the images label to `v3.28.1`, it worked successfully. I do not know what is the difference between `latest` and `v3.28.1` two images.  I wonder if it is possible to create a new tag - `edge`, which is consistent with master build, and `latest` tag means latest stable build? Thank you!

### Extra information and references

Running version v3.27.1 built on 2022-03-21T21:01:57.916Z (commit 5cc55c9) error logs

2022/03/22 08:00:29 INFO storage: merging by most recent 11100 hardcoded servers and 11106 servers read from /gluetun/servers.json
2022/03/22 08:00:29 INFO storage: Using ExpressVPN servers from file which are 3238h36m31s more recent
2022/03/22 08:00:29 INFO storage: Using Mullvad servers from file which are 4290h27m17s more recent
2022/03/22 08:00:29 INFO storage: Using Privado servers from file which are 1619h34m12s more recent
2022/03/22 08:00:29 INFO storage: Using PrivateVPN servers from file which are 5671h33m31s more recent
2022/03/22 08:00:29 INFO storage: Using ProtonVPN servers from file which are 1652h56m22s more recent
2022/03/22 08:00:29 ERROR failed validating VPN settings: provider settings validation failed: VPN provider name is not valid: "private internet access" can only be one of custom, ivpn, mullvad or windscribe
2022/03/22 08:00:29 INFO Shutdown successful

**Comment by Milssss** [comment]
I've been receiving this error all day. as well:
"2022/03/22 08:00:29 ERROR failed validating VPN settings: provider settings validation failed: VPN provider name is not valid: "private internet access" can only be one of custom, ivpn, mullvad or windscribe"

setting the tag to :v3.28.1 did fix this for me as well.. thank you for finding this

**Comment by qdm12** [comment]
So yesterday I pushed in this order latest, v3.27.1 and v3.28.1. My guess is watchtower pulled v3.27.1 which might have that PIA bug? Maybe you can configure it to only pull latest images instead of tagged ones?

The latest image corresponds to master.
You can also pull :v3 images which point to the latest chronological v3 release (so v3.28.1 here since I pushed it last).

**Comment by leo15dev** [comment]
> So yesterday I pushed in this order latest, v3.27.1 and v3.28.1. My guess is watchtower pulled v3.27.1 which might have that PIA bug? Maybe you can configure it to only pull latest images instead of tagged ones?
> 
> The latest image corresponds to master. You can also pull :v3 images which point to the latest chronological v3 release (so v3.28.1 here since I pushed it last).

My original docker images setting in docker-compose.yaml is 
    `image: qmcgaw/gluetun:latest`

The same problem happened in this issue https://github.com/qdm12/gluetun/issues/905#issue-1176116614
while the docker images setting in the issue is
    `image: qmcgaw/gluetun`

**Comment by qdm12** [comment]
Ok I found out what was wrong, my bad!!

v3.27.0 had a CI bug, where it would push to latest instead of v3.27.0. That's why v3.27.1 is logged for the latest image.
I re-triggered the master branch build so that will override the v3.27.1 bad tagging when the [build completes](https://github.com/qdm12/gluetun/actions/runs/2021237474).

I'll fix the CI in v3.27.1 and do a v3.27.2 release as well, with the CI fixed.

Sorry again for the disruption!
