### ISSUE TITLE
Feature request: VPN server support

### ISSUE THREAD

**Issue by gvkhna** [qdm12/gluetun#982]
I have some VMs on my unraid I would like to run through Gluetun. I tried shadow socks but the app I’m trying to isolate doesn’t respect these settings, proxies won’t work for this use case. 

Would it make sense to add a wire guard server into Gluetun, that will tunnel inbound connections out to my external VPN?

For clarity:

Windows VM (wireguard) -> GluetunVPN (docker/wireguard server) -> External VPN (Mullvad/Etc) -> Internet

I looked into adding a separate Wireguard docker container and adding that to the GluetunVPN network as well, an alternative which I’m exploring further. 

Seems like it would be great to have in Gluetun though as it’s trying to be a Swiss Army knife.

**Comment by qdm12** [comment]
Indeed, but there is an issue for this already #739 so please subscribe to that one 😉 

I'll try prioritizing this, although a Wireguard server involves fiddling with routes / ip level stuff unlike proxies, so that might get tricky for some niche setups. But for sure as an option, that sounds reasonable!
